-- RIDEX data snapshot
-- Generated by bin/export_db_snapshot.php
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `bookings`;
TRUNCATE TABLE `categories`;
TRUNCATE TABLE `gps_logs`;
TRUNCATE TABLE `payments`;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `vehicles`;

-- Table: categories
INSERT INTO `categories` (`id`, `name`, `description`) VALUES
  (1, 'Cars', 'Passenger cars and sedans'),
  (2, 'Bikes', 'Two-wheel vehicles'),
  (3, 'Luxury', 'Premium and high-end vehicles');

-- Table: users
INSERT INTO `users` (`id`, `name`, `first_name`, `last_name`, `email`, `password_hash`, `phone`, `address`, `date_of_birth`, `street`, `post_code`, `city`, `province`, `role`, `drivers_id`, `created_at`, `updated_at`) VALUES
  (1, 'Ridex Admin', NULL, NULL, 'rupikadangol@gmail.com', '$2y$10$ZNSNPOjYl9yPPPs8M2QSDeKV43eHlPx2osXbgnYHJn.R2xrxQxDFW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin', NULL, '2026-04-04 00:13:26', '2026-04-04 15:56:21'),
  (3, 'Ridex Admin', NULL, NULL, 'rupikadangole@gmail.com', '$2y$10$C.iqM1ZwDaatXwbf6lZRTePnoRcZw.WVjNhawiKWcLPKIdSsUOSVK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'user', NULL, '2026-04-04 00:35:14', '2026-04-04 03:40:17');

-- Table: vehicles
INSERT INTO `vehicles` (`id`, `category_id`, `vehicle_type`, `short_name`, `full_name`, `price_per_day`, `driver_age_requirement`, `image_path`, `number_of_seats`, `transmission_type`, `fuel_type`, `license_plate`, `status`, `gps_id`, `last_service_date`, `description`, `created_at`, `updated_at`) VALUES
  (1, 1, 'cars', 'L07', 'DEEPAL L07', 70, 21, 'images/deepal-l07-black.png', 5, 'automatic', 'electric', 'BAA-1237', 'available', NULL, NULL, 'DEEPAL L07 is an all-electric sedan with modern design and a comfortable luxury cabin.', '2026-04-02 18:05:31', '2026-04-04 00:27:08'),
  (2, 1, 'cars', 'L07', 'DEEPAL L07', 70, 21, 'images/deepal-l07-white.png', 5, 'automatic', 'electric', 'BAA-1238', 'available', NULL, NULL, 'DEEPAL L07 is an all-electric sedan with modern design and a comfortable luxury cabin.', '2026-04-02 18:05:31', '2026-04-04 00:27:09'),
  (3, 1, 'cars', 'Honda Elevate', 'Honda Elevate', 47, 21, 'images/honda-elevate-2.png', 5, 'automatic', 'petrol', 'BAA-1236', 'available', NULL, NULL, 'Honda Elevate is a versatile SUV designed for mixed road conditions with strong comfort and safety features.', '2026-04-02 07:59:29', '2026-04-04 00:27:09'),
  (4, 1, 'cars', 'Honda Elevate', 'Honda Elevate', 47, 21, 'images/honda-elevate-1.png', 5, 'automatic', 'petrol', 'BAA-1235', 'available', NULL, NULL, 'Honda Elevate is a versatile SUV designed for mixed road conditions with strong comfort and safety features.', '2026-04-02 07:59:29', '2026-04-04 00:27:09'),
  (5, 1, 'cars', 'Victoris', 'Maruti Suzuki Victoris', 52, 21, 'images/car1.png', 5, 'automatic', 'electric', 'BAA-1234', 'available', 'GPS-001', NULL, 'Maruti Suzuki Victoris combines comfort, safety, and modern technology for city and highway travel.', '2026-04-02 07:19:07', '2026-04-04 00:27:09'),
  (6, 2, 'bikes', 'Vespa', 'Vespa ZX 125', 30, 18, 'images/bikes.png', 2, 'N/A', 'petrol', 'BAA-1723', 'available', NULL, NULL, 'Vespa ZX 125 offers practical commuting performance with classic scooter styling.', '2026-04-02 18:05:31', '2026-04-04 00:27:09'),
  (7, 3, 'luxury', 'SL-Class (R231)', 'Mercedes-Benz SL-Class (R231)', 100, 21, 'images/luxury.png', 2, 'hybrid', 'petrol', 'BAA-1903', 'available', NULL, NULL, 'Mercedes-Benz SL-Class delivers premium grand touring comfort with high-performance engineering.', '2026-04-02 18:05:31', '2026-04-04 00:27:09'),
  (9, 3, 'luxury', 'Reserved', 'Mercedes-Benz SL-Class (R231)', 100, 21, 'images/luxury.png', 2, 'hybrid', 'petrol', 'BAA-1', 'reserved', NULL, NULL, 'Mercedes-Benz SL-Class delivers premium grand touring comfort with high-performance engineering.', '2026-04-04 08:50:02', '2026-04-04 08:50:02'),
  (10, 3, 'luxury', 'On Trip', 'Mercedes-Benz SL-Class (R231)', 100, 21, 'images/luxury.png', 2, 'hybrid', 'petrol', 'BAA-2', 'on_trip', NULL, NULL, 'Mercedes-Benz SL-Class delivers premium grand touring comfort with high-performance engineering.', '2026-04-04 08:55:37', '2026-04-04 08:55:37'),
  (12, 3, 'luxury', 'Overdue', 'Mercedes-Benz SL-Class (R231)', 100, 21, 'images/luxury.png', 2, 'hybrid', 'petrol', 'BAA-3', 'overdue', NULL, NULL, 'Mercedes-Benz SL-Class delivers premium grand touring comfort with high-performance engineering.', '2026-04-04 08:56:53', '2026-04-04 08:57:25'),
  (13, 3, 'luxury', 'Maintenance', 'Mercedes-Benz SL-Class (R231)', 100, 21, 'images/luxury.png', 2, 'hybrid', 'petrol', 'BAA-4', 'maintenance', NULL, NULL, 'Mercedes-Benz SL-Class delivers premium grand touring comfort with high-performance engineering.', '2026-04-04 13:42:38', '2026-04-04 13:42:38'),
  (14, 2, 'bikes', 'Reserved Test Bike', 'Vespa ZX 125', 30, 18, 'images/bikes.png', 2, 'N/A', 'petrol', 'BAA-1721', 'reserved', NULL, NULL, 'Vespa ZX 125 offers practical commuting performance with classic scooter styling.', '2026-04-04 15:47:43', '2026-04-04 15:47:57');

SET FOREIGN_KEY_CHECKS = 1;
